### ISSUE TITLE
关于开启弹幕数量统计后 在window 10 环境下 程序崩溃的问题

### ISSUE THREAD

**Issue by SmartJeffrey** [xbclub/BilibiliDanmuRobot-Core#31]
+++++++++++++++++++
崩溃时后台输出：
```
panic: time: missing Location in call to Time.In

goroutine 93 [running]:
time.Time.In(...)
        time/time.go:1146
github.com/xbclub/BilibiliDanmuRobot-Core/model.(*defaultDanmuCntModel).GetDateStr(0xc0003c5080?, 0x0)
        github.com/xbclub/BilibiliDanmuRobot-Core@v1.1.16/model/userDanmuCounter.go:47 +0x165
github.com/xbclub/BilibiliDanmuRobot-Core/logic/danmu.BadgeActiveCheckProcess({0xc0004b15e8, 0x6}, {0xc0004b15b0, 0x10}, {0xc000370000?, 0xc000065fd0?}, 0xc0004008a0, {0xc000304058, 0x1, 0x1})
        github.com/xbclub/BilibiliDanmuRobot-Core@v1.1.16/logic/danmu/badgeActivate.go:16 +0x58
created by github.com/xbclub/BilibiliDanmuRobot-Core/logic/danmu.StartDanmuLogic in goroutine 53
        github.com/xbclub/BilibiliDanmuRobot-Core@v1.1.16/logic/danmu/danmu_bullet.go:81 +0x89c
```

+++++++++++++++++++
定位代码文件：model/userDanmuCounter.go

+++++++++++++++++++
相关函数：
```
func (m *defaultDanmuCntModel) GetDateStr(daysFromToday int) string {
	beijingLocation, err1 := time.LoadLocation("Asia/Shanghai")
	if err1 != nil {
		logx.Error(err1)
	}
	dateStr := time.Now().In(beijingLocation).AddDate(0, 0, -daysFromToday).Format("2006-01-02")
	logx.Info(dateStr)
	return dateStr
}
```
+++++++++++++++++++
怀疑问题出现在 time.LoadLocation("Asia/Shanghai") ，因为没有该时区，考虑是否可以在载入失败时，创建默认时区，修改该函数代码为：
```
func (m *defaultDanmuCntModel) GetDateStr(daysFromToday int) string {
	beijingLocation, err1 := time.LoadLocation("Asia/Shanghai")
	if err1 != nil {
		beijingLocation = time.FixedZone("UTC", 8*3600)
		logx.Error(err1)
	}
	dateStr := time.Now().In(beijingLocation).AddDate(0, 0, -daysFromToday).Format("2006-01-02")
	logx.Info(dateStr)
	return dateStr
}
```

一点拙见，不喜轻喷

**Comment by xbclub** [comment]
了解 有空我排查下

**Comment by xbclub** [comment]
如果你方便测试下，欢迎pr，我最近比较忙可能无法及时排查

**Comment by xbclub** [comment]
我刚想起来 有个难崩的事 我手头没Windows

**Comment by xbclub** [comment]
已修复
